name: fit_quest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  app_links: ^6.4.0
  app_links_platform_interface: 2.0.2
  auto_size_text: 3.0.0
  badges: ^3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  chewie: ^1.11.1
  collection: ^1.19.1
  csslib: ^1.0.2
  csv: 6.0.0
  dropdown_button2: 2.3.9
  easy_debounce: ^2.0.3
  emoji_flag_converter: 1.1.0
  file_picker: ^10.1.0
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: ^4.5.2
  flutter_blurhash: 0.8.2
  flutter_cache_manager: 3.4.1
  flutter_plugin_android_lifecycle: ^2.0.27
  flutter_rating_bar: 4.0.1
  flutter_secure_storage: ^10.0.0-beta.4
  flutter_secure_storage_linux: ^2.0.1
  flutter_secure_storage_macos: ^4.0.0
  flutter_secure_storage_platform_interface: ^2.0.1
  flutter_secure_storage_web: ^2.0.0
  flutter_secure_storage_windows: ^4.0.0
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  functions_client: ^2.4.1
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  gotrue: ^2.11.1
  hive: 2.2.3
  html: ^0.15.5+1
  image_picker: 1.1.2
  image_picker_android: ^0.8.12+22
  image_picker_for_web: ^3.0.6
  image_picker_ios: ^0.8.12+2
  image_picker_linux: ^0.2.1+2
  image_picker_macos: ^0.2.1+2
  image_picker_platform_interface: ^2.10.1
  image_picker_windows: 0.2.1+1
  intl: 0.19.0
  json_path: ^0.7.5
  mapbox_search: ^4.3.1
  mime_type: ^1.0.1
  octo_image: 2.1.0
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.16
  path_provider_foundation: ^2.4.1
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  plugin_platform_interface: 2.1.8
  postgrest: ^2.4.1
  provider: ^6.1.4
  realtime_client: ^2.4.2
  rxdart: 0.27.7
  share_plus: ^10.1.4
  share_plus_platform_interface: ^5.0.2
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.9
  shared_preferences_foundation: ^2.5.4
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_windows: 2.4.1
  sign_in_with_apple: ^7.0.1
  sign_in_with_apple_platform_interface: ^2.0.0
  sign_in_with_apple_web: ^3.0.0
  sqflite: ^2.4.2
  sqflite_common: ^2.5.5
  storage_client: ^2.3.1
  substring_highlight: 1.0.33
  supabase: ^2.6.3
  supabase_flutter: ^2.8.4
  synchronized: ^3.3.1
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.15
  url_launcher_ios: ^6.3.3
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.2
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: ^2.4.0
  url_launcher_windows: ^3.1.4
  video_player: ^2.9.5
  video_player_android: ^2.8.2
  video_player_avfoundation: ^2.7.0
  video_player_platform_interface: ^6.3.0
  video_player_web: ^2.3.4
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.4
  webview_flutter_platform_interface: 2.10.0
  webview_flutter_wkwebview: ^3.18.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.2
  rxdart: 0.27.7
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  image: ^4.5.4
  lints: ^5.1.1
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

